Repository go-xorm/xorm, pull requests merged in 2018-06, with the labels that each got.

#996 Change pgx driver
  dialect_postgres.go
  dialect_postgres_test.go
  xorm.go
Labels: kind/feature

#1015 Add support for mulitple transactions on one session
  session_tx.go
  session_tx_test.go
Labels: enhancement

#1012 Fix BUG: Update statement build function should ingore ONLYFROMDB fields
  statement.go
  statement_test.go
Labels: kind/bug
