Repository go-xorm/xorm, pull requests merged in 2018-04, with the labels that each got.

#874 Join add TableName interface support
  session_find_test.go
  session_get_test.go
  statement.go
Labels: enhancement

#875 chore(postgres): support add schema as prefix of table name
  engine.go
Labels: enhancement

#876 Add SetSchema for engine
  circle.yml
  dialect_postgres.go
  engine.go
  engine_table.go
  interface.go
  rows.go
  rows_test.go
  session.go
  session_cond_test.go
  session_delete.go
  session_exist.go
  session_exist_test.go
  session_find_test.go
  session_get.go
  session_get_test.go
  session_insert.go
  session_insert_test.go
  session_pk_test.go
  session_query_test.go
  session_raw_test.go
  session_schema.go
  session_stats_test.go
  session_tx_test.go
  session_update.go
  session_update_test.go
  statement.go
  tag_extends_test.go
  types_test.go
  xorm_test.go
Labels: enhancement, testing

#878 Add test for resolve #797
  session_get_test.go
Labels: testing

#879 Add test for (id) replace
  session_get_test.go
Labels: kind/bug, testing

#880 Add test for count with orderby and limit
  session_find.go
  session_query.go
  session_stats_test.go
  statement.go
Labels: kind/bug, testing

#882 Fix id condition not used bug
  helpers.go
  session_cols.go
  session_get_test.go
  session_insert.go
  session_query.go
  session_update.go
  statement.go
Labels: kind/bug

#884 refactor buildUpdates
  session_update.go
  statement.go
Labels: kind/refactor

#883 Add test for update map
  session_update_test.go
Labels: testing

#885 Add test for tablename
  engine_table_test.go
Labels: testing

#886 add test and remove unused warn log
  engine_cond.go
  error.go
  interface.go
  session.go
  session_cols_test.go
Labels: testing

#887 fix tablename bug
  engine_table.go
  session_find.go
  session_find_test.go
  session_insert.go
  statement.go
Labels: kind/bug

#888 fix update map with table name
  engine.go
  interface.go
  session_delete.go
  session_find.go
  session_get.go
  session_insert.go
  session_update.go
  session_update_test.go
  statement.go
  tag_cache_test.go
  xorm.go
Labels: enhancement

#904 add test for insert anonymous struct
  session_insert_test.go
Labels: testing

#916 fix some bug on extends find
  engine.go
  session_find_test.go
Labels: kind/bug

#917 Cache limit test
  session_find_test.go
  xorm.go
Labels: testing

#918 Add testing for update via condition bean
  session_update_test.go
Labels: testing
