Repository go-xorm/xorm, pull requests merged in 2018-09, with the labels that each got.

#1091 Add more methods for EngineInterface
  engine.go
  engine_group.go
  engine_maxlife.go
  interface.go
  xorm.go
Labels: enhancement

#1093 enhancement: auto-transaction
  .gitignore
  transaction.go
  transancation_test.go
Labels: kind/feature

#1099 add test for <- tag
  tag_test.go
Labels: testing

#1100 Add unvalid pk test
  session_pk_test.go
Labels: testing

#1102 Get adds context cache feature
  README.md
  README_CN.md
  context_cache.go
  session.go
  session_get.go
  session_get_test.go
  statement.go
Labels: kind/feature
