Repository go-xorm/xorm, pull requests merged in 2018-10, with the labels that each got.

#1092 Add drone ci
  .drone.yml
Labels: testing

#1114 Add query slice string
  session_query.go
  session_query_test.go
Labels: kind/feature

#1120 add mysql utf8mb4 tests
  .drone.yml
Labels: testing

#1125 Add version uint type support
  session.go
  session_insert.go
  session_update.go
  tag_version_test.go
Labels: kind/bug
