Repository go-xorm/xorm, pull requests merged in 2019-01, with the labels that each got.

#1186 Fix exporting values into Postgres
  dialect_postgres.go
  engine.go
Labels: kind/bug

#1198 Add circleci 2 support
  .circleci/config.yml
  circle.yml
Labels: testing

#1193 Add context support
  engine.go
  engine_context.go
  engine_context_test.go
  interface.go
  session.go
  session_context.go
  session_context_test.go
  session_raw.go
  session_schema.go
  session_tx.go
  xorm.go
Labels: enhancement

#1194 Add tests for get interface
  session_get_test.go
Labels: testing

#1151 Add lasterror on statement to return errors when chain operations
  error.go
  session_delete.go
  session_exist.go
  session_find.go
  session_get.go
  session_iterate.go
  session_update.go
  session_update_test.go
  statement.go
Labels: enhancement

#1002 Join support builder
  session_query_test.go
  statement.go
Labels: enhancement

#940 Add insert map support
  session_insert.go
  session_insert_test.go
Labels: enhancement

#1101 fix #1075 and replace #1076
  engine_group.go
  session.go
  session_raw.go
Labels: kind/bug

#1199 Add more tests for TableName
  session_stats_test.go
Labels: testing

#1200 remove unused_code
  rows.go
Labels: testing

#1201 add more tests for rows
  rows_test.go
Labels: testing

#1203 Add mssql ci test
  .circleci/config.yml
  engine_table.go
  processors_test.go
  session_delete_test.go
  session_exist.go
  session_get_test.go
  session_insert.go
  session_insert_test.go
  session_query_test.go
  statement.go
  tag_extends_test.go
  test_mssql.sh
  types.go
  types_test.go
  xorm_test.go
Labels: testing

#1205 fix mssql connstr bug
  dialect_mssql.go
  dialect_mssql_test.go
Labels: kind/bug

#1206 improve tests
  session_context_test.go
Labels: testing

#1210 Update go mod
  .circleci/config.yml
  go.mod
  go.sum
Labels: build

#1211 update go mod
  go.mod
  go.sum
Labels: build
