Repository go-xorm/xorm, pull requests merged in 2019-03, with the labels that each got.

#1246 Update README.md file
  README.md
  README_CN.md
Labels: kind/docs

#1249 add deleted condition for Update operation
  session_update.go
  session_update_test.go
Labels: kind/bug

#1248 Make json handler as interface
  engine_cond.go
  json.go
  session.go
  session_convert.go
  statement.go
  types_test.go
Labels: enhancement
