Repository go-xorm/xorm, pull requests merged in 2019-06, with the labels that each got.

#1315 Fix show SQL when set logger
  engine.go
Labels: kind/bug

#1327 Move depends package from github.com to customize domain
  .circleci/config.yml
  .drone.yml
  README.md
  cache_lru.go
  cache_lru_test.go
  cache_memory_store.go
  dialect_mssql.go
  dialect_mssql_test.go
  dialect_mysql.go
  dialect_oracle.go
  dialect_postgres.go
  dialect_postgres_test.go
  dialect_sqlite3.go
  engine.go
  engine_cond.go
  engine_group.go
  engine_table.go
  go.mod
  go.sum
  helpers.go
  interface.go
  logger.go
  rows.go
  session.go
  session_cols.go
  session_cols_test.go
  session_cond.go
  session_cond_test.go
  session_convert.go
  session_delete.go
  session_delete_test.go
  session_exist.go
  session_find.go
  session_find_test.go
  session_get.go
  session_get_test.go
  session_insert.go
  session_pk_test.go
  session_query.go
  session_query_test.go
  session_raw.go
  session_schema.go
  session_stats_test.go
  session_tx_test.go
  session_update.go
  session_update_test.go
  statement.go
  statement_test.go
  syslogger.go
  tag.go
  tag_extends_test.go
  tag_id_test.go
  tag_test.go
  types.go
  types_test.go
  xorm.go
  xorm_test.go
Labels: build

#1334 Fix no rows return error when close
  rows.go
  rows_test.go
Labels: kind/bug

#1284 Allow adding prefix for fields with `extends` tag
  engine.go
  tag.go
  tag_extends_test.go
Labels: enhancement
