Repository go-xorm/xorm, pull requests merged in 2019-07, with the labels that each got.

#1346 reflect.Value.Bytes() should only be called when reflect.Value.Kind()…
  session_convert.go
Labels: kind/bug

#1350 Update go mod
  go.mod
  go.sum
Labels: build

#1363 Make sure timeout will really happen in context timeout test
  engine_context_test.go
  session_context_test.go
Labels: testing

#1360 Remove QuoteStr() usage
  engine.go
  helpers.go
  helpers_test.go
  session_insert.go
  session_update.go
  session_update_test.go
  statement.go
  statement_test.go
Labels: enhancement

#1365 Document for FindAndCount()
  README.md
Labels: kind/docs

#890 fix error when get null var
  session_get.go
  session_get_test.go
  tag_test.go
Labels: kind/bug

#1305 Add tests for get var
  session_get_test.go
Labels: testing

#1374 update drone
  .drone.yml
Labels: build

#1375 fix bugs
  session_find.go
  session_get.go
Labels: kind/bug
